INDEXTSX="src/index.tsx"
INDEXHTML="src/index.html"
APPTSX="src/App.tsx"
APPCSS="src/App.global.css"
PACKAGEMANAGER="src/package.json"
HOMETSX="src/component/home.tsx"
CHECKBOXFILTERTSX="src/component/templates/checkbox.filter.tsx"
DIALOGFILTERTSX="src/component/templates/dialog.filter.tsx"
MINIDRAWERTSX="src/component/templates/mini-drawer.tsx"
OFFLINETSX="src/component/templates/offline.tsx"
POPULARTSX="src/component/templates/popular.tsx"
TABSTSX="src/component/templates/tabs.tsx"

alias addpackagemanager="git add $PACKAGEMANAGER && git commit"
alias addhome="git add $HOMETSX && git commit"
alias addcheckboxfilter="git add $CHECKBOXFILTERTSX && git commit"
alias adddialogfilter="git add $DIALOGFILTERTSX && git commit"
alias addminidrawer="git add $MINIDRAWERTSX && git commit"
alias addoffline="git add $OFFLINETSX && git commit"
alias addpopular="git add $POPULARTSX && git commit"
alias addtabs="git add $TABSTSX && git commit"

alias push="git push origin master"
