SRC="src"
COMPONENT="$SRC/component"
TEMPLATE="$SRC/component/templates"
INDEXTSX="$SRC/index.tsx"
INDEXHTML="$SRC/index.html"
APPTSX="$SRC/App.tsx"
PACKAGEMANAGER="$SRC/package.json"
HOMETSX="$COMPONENT/home.tsx"
CHECKBOXFILTERTSX="$TEMPLATE/checkbox.filter.tsx"
DIALOGFILTERTSX="$TEMPLATE/dialog.filter.tsx"
MINIDRAWERTSX="$TEMPLATE/mini-drawer.tsx"
OFFLINETSX="$TEMPLATE/offline.tsx"
POPULARTSX="$TEMPLATE/popular.tsx"
TABSTSX="$TEMPLATE/tabs.tsx"

alias push="git push origin master"
alias pull="git pull origin master"

alias addall="git add . && git commit && git push origin master"

alias addindextsx="git add $INDEXTSX && git commit && git push origin master"
alias addindexhtml="git add $INDEXHTML && git commit && git push origin master"
alias addapp="git add $APPTSX && git commit && git push origin master"
alias addpackagemanager="git add $PACKAGEMANAGER && git commit && git push origin master"
alias addhome="git add $HOMETSX && git commit && git push origin master"
alias addcheckboxfilter="git add $CHECKBOXFILTERTSX && git commit && git push origin master"
alias adddialogfilter="git add $DIALOGFILTERTSX && git commit && git push origin master"
alias addminidrawer="git add $MINIDRAWERTSX && git commit && git push origin master"
alias addoffline="git add $OFFLINETSX && git commit && git push origin master"
alias addpopular="git add $POPULARTSX && git commit && git push origin master"
alias addtabs="git add $TABSTSX && git commit && git push origin master"

